### ISSUE TITLE
Polir les arguments de SOStab

### ISSUE THREAD

**Issue by matteo-tacchi** [droste89/SOStab#3]
Je pense que c'est mieux si les chaînes de caractères nommant les variables n'apparaissent pas dans le premier appel de SOStab. L'idéal serait de ne les mettre que lorsqu'elles sont utiles (je te laisse voir où exactement, on peut s'appeler pour en discuter si tu veux)

**Comment by matteo-tacchi** [comment]
Aussi : mettre obligatoirement "x_1" et "x_2" dans les variables quand on plot, c'est un peu sous-optimal : ça devrait être un réglage par défaut de la toolbox d'afficher les variables x_{ind1}, x_{ind2} sur les axes du plot, à modifier seulement sur demande de l'utilisateur

**Comment by droste89** [comment]
Related commit : 6a0e3df461719177c6a29a2e6e26db93ca192ad2
