### ISSUE TITLE
changement de taille des tableaux

### ISSUE THREAD

**Issue by matteo-tacchi** [droste89/SOStab#5]
Pour les contraintes SoS, Matlab me dit dans l'oreillette que changer la taille d'un tableau en cours de calcul est très cher. À la place, il me propose de créer dès le départ un tableau de la bonne taille (avec des 1 ou des 0) et d'en modifier les entrées dans les boucles. Ça peut être bien à faire pour gagner en efficacité

**Comment by droste89** [comment]
Difficille à mettre, parce que comment initialiser un tableau de type "contraintes sos", de taille donnée ?

**Comment by matteo-tacchi** [comment]
Je pense que ce qui prend de la mémoire c'est de rajouter des entrées au tableau, pas de changer le type des entrées. Du coup on pourrait créer un tableau de type "double" (avec pour valeur 0 à chaque entrée) avec la bonne taille, et à chaque étape de la boucle on modifie une nouvelle entrée, la changeant de 0 à une contrainte SoS. Non ?

**Comment by droste89** [comment]
Non : si tu crées un tableau de double, tu ne peut pas changer son type après coup.
