### ISSUE TITLE
Moments

### ISSUE THREAD

**Issue by matteo-tacchi** [droste89/SOStab#6]
Au lieu de définir y par une suite de 1 et réallouer la valeur 0 à tous les moments avec une puissance impaire, j'aurais plutôt définit y par une suite de 0, rien fait dès qu'il y a un moment avec une puissance impaire, et modifié la valeur de y seulement aux puissances paires, non ?

**Comment by droste89** [comment]
Pas trivial, parce que l'intégration d'une fonction à plusieurs variables c'est un produit d'intégrations, donc c'est plus pratique de partir de 1 et multiplier par la valeur de chaque intégration. Le calcul des moments a une durée négligeable de toute façon.

**Comment by matteo-tacchi** [comment]
Effectivement, je comprends mieux, ça fait sens.
